coding/hannovit/core/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('dashboard/', include('demoapp.urls',namespace='demoapp')),
    path('admin/', admin.site.urls),
]

coding/hannovit/core/demoapp/urls.py
from django.urls import path

from demoapp.views import (
    getlist,
    edit_data,
    delete_data,
    add_data,
    detail_data
)


app_name= 'demoapp'

urlpatterns =[
    path('view/', getlist, name='view'),
    path('detail/<int:id>/', detail_data, name='detail'),
    path('edit/<int:id>/', edit_data, name='edit'),
    path('delete/<int:id>/', delete_data, name='delete'),
    path('add/', add_data, name='add'),
]

coding/hannovit/core/demoapp/models.py
from django.db import models



class Patient(models.Model):
    SEX_CHOICES = (
    ('female', 'female',),
    ('male', 'male',)
    
    )
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    gender = models.CharField(max_length=10,choices=SEX_CHOICES,)
    dob = models.DateField(max_length=20)


    def __str__(self):
        return self.firstname

coding/hannovit/core/demoapp/forms.py
from django import forms
from .models import Patient
from django.forms import ModelForm

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__' # ['firstname','lastname','gender','dob'] #'__all__'



class EditPatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['firstname','dob'] #'__all__'



    

coding/hannovit/core/demoapp/views.py
from django.shortcuts import render, redirect
from .models import Patient
from .forms import PatientForm,EditPatientForm
import json
from django.http import JsonResponse
from django.contrib.sites.shortcuts import get_current_site

def getlist(request):
    try:
        data = Patient.objects.all()
    except Patient.DoesNotExist as e:
        print(e)
        return "Does Not Exist"
    return render(request, 'views/index.html',{"data":data})


def edit_data(request,id):
    data = Patient.objects.get(id=id)
    if request.method == 'POST':
        form = EditPatientForm(request.POST,instance=data)
        if form.is_valid():
            form.save()
            return redirect('/dashboard/view')
        return render(request,'views/edit.html',{"data":data})
    return render(request,'views/edit.html',{"data":data})
    
   

def delete_data(request,id):
    if request.method == 'POST':
        try:
            data = Patient.objects.get(id=id)
            data.delete()
            payload = {'deleted': True}
        except Patient.DoesNotExist:
            return "Data DoesNot Exist"
    return JsonResponse(payload)

def detail_data(request,id):
        try:
            data = Patient.objects.get(id=id)
        except Patient.DoesNotExist as e:
            print(e)
            return "Value error"
        return render(request, 'views/detail.html', {'data':data})

def add_data(request):
    if request.method == 'POST':
        form = PatientForm(request.POST or None)
        if form.is_valid():
            print("valid")
            form.save()
        
            return redirect('/dashboard/view')
   
        return render(request,'views/add.html')
    return render(request,'views/add.html')
    

coding/hannovit/core/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Health</title>
      {% include 'base/css.html' %}
      
    </head>
    <body>
       
        {% block content %}{% endblock %}

    </body>
    {% include 'base/js.html' %}
    {% block scripts %}{% endblock %}
    

   
  </html>

coding/hannovit/core/templates/base/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

coding/hannovit/core/templates/base/js.html
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

coding/hannovit/core/templates/views/add.html
{% extends "base.html" %}
{% load static %}


{% block content %}
     <!-- form -->
    <div class="container mt-2">
      <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #007bff;">
        <div>Add Patient</div>
      </nav>


       <div class="mt-2">
        <form  action="{% url 'demoapp:add' %}"  method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col">
              
              <input type="text" id="firstnameid" name="firstname" class="form-control" placeholder="First name" required>
            </div>
            <div class="col">
              <input type="text" id="lastnameid" name="lastname" class="form-control" placeholder="Last name" required>
            </div>
          </div>
  
          <div class="row">
              <div class="col">
                  <label for="inputgender">Gender</label>
                  <select id="inputgenderid" name="gender" class="form-control" required>
                    <option disabled selected value="">Choose...</option>
                    <option value="male">MALE</option>
                    <option value="female">FEMALE</option>
                  </select>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
              </div>
  
              <div class="col">
                  <label for="inputdob">DOB</label>
                <div class="input-group date" data-provide="datepicker">
                  <input type="date" id="datedobid" name="dob" class="form-control" required>
                  <div class="input-group-addon">
                      <span class="glyphicon glyphicon-th"></span>
                  </div>
                  </div>
  
              </div>
          </div>
            <button type="submit" class="btn btn-primary mt-2" value="submit">Save</button>
      </form>
       </div>
    </div>
    {% endblock %}

coding/hannovit/core/templates/views/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    delete data
</body>
</html>

coding/hannovit/core/templates/views/detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
     <!-- form -->
    <div class="container mt-2">
      <nav class=" navbar-light bg-light2" style="    background-color: #007bff;">
        <div  class="d-flex justify-content-end">

        <a class="navbar-brand " href="{% url 'demoapp:edit' data.id%}">Edit</a>
      </div>
      </nav>
      
            <div class="row">
              <div class="col-12 col-sm-6">
               <div>
                Name:                                                                                                                                                                                                                                                                                                                                                                                                                                                     
               </div>
              <div>
                DOb:
              </div>
              </div>
              <div class="col-12 col-sm-6">
               <div>
                {{data.firstname}}
               </div>
               <div>
                {{data.dob}}
               </div>
              </div>
            </div>
      
    
        
    </div>
    {% endblock %}

coding/hannovit/core/templates/views/edit.html
{% extends "base.html" %}
{% load static %}


{% block content %}
     <!-- form -->
    <div class="container mt-2">
        <nav class=" navbar-light" style="background-color: #007bff;">
            <div  class="">
             <div> upated patient</div>
          </div>
          </nav>

    <div class="mt-2">

    <form  action="{% url 'demoapp:edit' data.id %}"  id="form_agentId"   method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col">
            <input type="text" id="firstname" name="firstname" value="{{data.firstname}}" class="form-control" placeholder="First name" required>
          </div>
        
        </div>

            <div class="row">
              <div class="col">
                <label for="inputdob">DOB</label>
              <div class="input-group date" data-provide="datepicker">
                <input type="date" id="datedobid" value="{{data.dob}}" name="dob" class="form-control" required>
                <div class="input-group-addon"> 
                    <span class="glyphicon glyphicon-th"></span>
                </div>                                                                                                                                                                                                                                                              
                </div>

            </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary mt-4">Save</button>
    </form>
</div>
    </div>
    {% endblock %}

coding/hannovit/core/templates/views/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container mt-4">
        <div class="d-flex justify-content-end">
            <a  href="{% url 'demoapp:add' %}" >
                <i class="fa fa-user-plus"></i>
            </a>
        </div>
       
       
          <table class="table mt-2" id ="usertable">
            <thead class="table-primary44" style="background-color: #007bff;">
              <tr>
                <th scope="col">id</th>
                <th scope="col">Patient Name</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {%  for item in data %}
              <tr id="item-{{item.id}}">
                <td>{{item.id}}</td>
                <td>{{item.firstname}}</td>
                <td>{{item.dob}}</td>
                <td>
                  <a  href="{% url 'demoapp:detail' item.id %}" >Views</a>
                    <button type="button" data-object-id='{{item.id}}' class="btn btn-danger deletedata-id">Delete</button>
                </td>
              </tr>
              
              {% endfor %}
            </tbody>
        </table>
      
</div>
  {% endblock %}



  {% block scripts %}

  <script>
    //delete agent data
    $(function(){
     
    $('.deletedata-id').on('click', function (e) {
      e.preventDefault();
      var token = '{{csrf_token}}';
      let object_id = $(this).attr('data-object-id');
      console.log('object_id',object_id);
      $.ajax({
            headers: { "X-CSRFToken": token },
            url : '/dashboard/delete/'+object_id+'/',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
            type : "POST" , 
            data:{id:object_id},
            dataType: 'json', 
            success : function(res) {
            console.log("sucess ") 
            if (res.deleted){
              //console.log(res.deleted)
              $("#usertable #item-" + object_id).remove();
            }
            
      
              
           } ,
             
            error : function(xhr,errmsg,err) {
            alert("something")
            }
      });
     
      
  });


  
});


  </script>

  {% endblock %}